# Generated by Django 4.1.4 on 2024-03-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('is_open', models.BooleanField(verbose_name='Открыт')),
                ('year', models.IntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
                'ordering': ['number', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Enrollee',
            fields=[
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('snils', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='СНИЛС')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('gpa', models.FloatField(verbose_name='Средний Балл')),
                ('application_date', models.DateField(null=True, verbose_name='Дата Подачи Документов')),
                ('current_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.current', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
                'ordering': ['full_name', 'inn', 'gpa', 'current_id', 'application_date'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название')),
                ('seats_amount', models.IntegerField(default=25, verbose_name='Количество Мест')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnrolleeSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default='3', max_length=1, verbose_name='Приоритет')),
                ('is_enrolled', models.BooleanField(default=False, verbose_name='Зачислен')),
                ('enrollee_snils', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enrollee', verbose_name='Абитуриент')),
                ('speciality_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.speciality', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Выбранная специальность',
                'verbose_name_plural': 'Выбранные специальности',
                'ordering': ['enrollee_snils', 'priority'],
            },
        ),
    ]
