# Generated by Django 4.1.4 on 2024-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current',
            options={'ordering': ['id', 'closing_date'], 'verbose_name': 'Набор Студентов', 'verbose_name_plural': 'Наборы Студентов'},
        ),
        migrations.AlterModelOptions(
            name='enrolleespeciality',
            options={'ordering': ['enrollee_snils', 'speciality_name'], 'verbose_name': 'Выбранная Специальность', 'verbose_name_plural': 'Выбранные Специальности'},
        ),
        migrations.RemoveField(
            model_name='current',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='current',
            name='number',
        ),
        migrations.RemoveField(
            model_name='current',
            name='year',
        ),
        migrations.RemoveField(
            model_name='enrolleespeciality',
            name='priority',
        ),
        migrations.AddField(
            model_name='current',
            name='closing_date',
            field=models.DateField(null=True, verbose_name='Дата Закрытия Набора'),
        ),
        migrations.AddField(
            model_name='current',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolleespeciality',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='Приоритетная'),
        ),
    ]
