# Generated by Django 4.1.4 on 2024-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_current_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='closing_date',
            field=models.DateField(verbose_name='Дата Закрытия Набора'),
        ),
    ]
