# Generated by Django 4.1.4 on 2024-03-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_current_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='application_date',
            field=models.DateField(verbose_name='Дата Подачи Документов'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='current_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.current', verbose_name='Набор'),
        ),
    ]
