# Generated by Django 4.1.4 on 2024-04-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_enrollee_application_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current',
            new_name='Recruitment',
        ),
        migrations.AlterModelOptions(
            name='enrollee',
            options={'ordering': ['full_name', 'inn', 'gpa', 'recruitment', 'application_date'], 'verbose_name': 'Абитуриент', 'verbose_name_plural': 'Абитуриенты'},
        ),
        migrations.AlterModelOptions(
            name='enrolleespeciality',
            options={'ordering': ['enrollee', 'speciality'], 'verbose_name': 'Выбранная Специальность', 'verbose_name_plural': 'Выбранные Специальности'},
        ),
        migrations.RenameField(
            model_name='enrollee',
            old_name='current_id',
            new_name='recruitment',
        ),
        migrations.RenameField(
            model_name='enrolleespeciality',
            old_name='speciality_name',
            new_name='speciality',
        ),
        migrations.RemoveField(
            model_name='enrolleespeciality',
            name='enrollee_snils',
        ),
        migrations.AddField(
            model_name='enrolleespeciality',
            name='enrollee',
            field=models.ForeignKey(default='snils1', on_delete=django.db.models.deletion.CASCADE, related_name='selected_specialities', to='api.enrollee', verbose_name='Абитуриент'),
            preserve_default=False,
        ),
    ]
