# Generated by Django 4.1.4 on 2024-04-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_current_recruitment_alter_enrollee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitment',
            options={'ordering': ['name', 'closing_date'], 'verbose_name': 'Набор Студентов', 'verbose_name_plural': 'Наборы Студентов'},
        ),
        migrations.RemoveField(
            model_name='enrollee',
            name='recruitment',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='id',
        ),
        migrations.AddField(
            model_name='speciality',
            name='education_period',
            field=models.CharField(blank=True, max_length=50, verbose_name='Срок Обучения'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='enrollee',
            name='recruitment',
            field=models.ForeignKey(default='2024', on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='api.recruitment', verbose_name='Набор'),
        ),
    ]
