# Generated by Django 4.1.4 on 2024-05-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_recruitment_options_remove_recruitment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruitment', verbose_name='Набор'),
        ),
    ]
