# Generated by Django 4.1.4 on 2024-05-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_enrollee_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Код'),
        ),
    ]
